# Generated by Django 6.0.3 on 2026-04-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_post_cover_filename_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
