# Generated by Django 4.2.30 on 2026-04-27 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(db_column='ma_sach', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='tieu_de', max_length=255)),
                ('author', models.CharField(blank=True, db_column='tac_gia', max_length=255, null=True)),
                ('category', models.CharField(blank=True, db_column='the_loai', max_length=100, null=True)),
                ('cover_image', models.CharField(blank=True, db_column='anh_bia', max_length=255, null=True)),
                ('description', models.TextField(blank=True, db_column='mo_ta', null=True)),
                ('avg_rating', models.DecimalField(db_column='diem_trung_binh', decimal_places=1, default=0.0, max_digits=3)),
                ('total_reviews', models.IntegerField(db_column='tong_luot_danh_gia', default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True, db_column='ngay_tao')),
            ],
            options={
                'db_table': 'sach',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BookReview',
            fields=[
                ('id', models.AutoField(db_column='ma_danh_gia', primary_key=True, serialize=False)),
                ('review_title', models.CharField(blank=True, db_column='tieu_de_review', max_length=255, null=True)),
                ('review_body', models.TextField(blank=True, db_column='noi_dung_review', null=True)),
                ('stars', models.IntegerField(blank=True, db_column='so_sao', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='ngay_tao')),
            ],
            options={
                'db_table': 'danh_gia_chi_tiet',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(db_column='ma_chuong', primary_key=True, serialize=False)),
                ('order', models.IntegerField(db_column='thu_tu_chuong')),
                ('title', models.CharField(db_column='tieu_de_chuong', max_length=255)),
                ('content', models.TextField(blank=True, db_column='noi_dung', null=True)),
            ],
            options={
                'db_table': 'chuong_sach',
                'ordering': ['book_id', 'order'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('message_id', models.AutoField(db_column='ma_tin_nhan', primary_key=True, serialize=False)),
                ('sender_name', models.CharField(db_column='ten_nguoi_gui', max_length=255)),
                ('sender_email', models.CharField(db_column='email_nguoi_gui', max_length=255)),
                ('content', models.TextField(db_column='noi_dung')),
                ('send_time', models.DateTimeField(auto_now_add=True, db_column='ngay_gui')),
            ],
            options={
                'db_table': 'tin_nhan_lien_he',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Media',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AlterModelTable(
            name='user',
            table='nguoi_dung',
        ),
    ]
