# Generated by Django 4.2.30 on 2026-05-09 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_book_bookreview_chapter_contactmessage_delete_media_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.AutoField(db_column='ma_phieu_muon', primary_key=True, serialize=False)),
                ('borrow_date', models.DateTimeField(auto_now_add=True, db_column='ngay_muon')),
                ('due_date', models.DateTimeField(db_column='han_tra')),
                ('return_date', models.DateTimeField(blank=True, db_column='ngay_tra_thuc_te', null=True)),
                ('status', models.CharField(db_column='trang_thai', default='ChoDuyet', max_length=50)),
                ('note', models.TextField(blank=True, db_column='ghi_chu', null=True)),
                ('borrower_name', models.CharField(blank=True, db_column='ten_nguoi_muon', max_length=255, null=True)),
                ('book_name', models.CharField(blank=True, db_column='ten_sach', max_length=255, null=True)),
                ('condition_borrow', models.CharField(db_column='tinh_trang_luc_muon', default='Nguyên vẹn', max_length=255)),
                ('condition_return', models.CharField(blank=True, db_column='tinh_trang_luc_tra', max_length=255, null=True)),
                ('borrow_image', models.CharField(blank=True, db_column='hinh_minh_chung_muon', max_length=255, null=True)),
                ('return_image', models.CharField(blank=True, db_column='hinh_minh_chung_tra', max_length=255, null=True)),
                ('admin_note', models.TextField(blank=True, db_column='ghi_chu_admin', null=True)),
            ],
            options={
                'db_table': 'phieu_muon',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='bookreview',
            options={'managed': True, 'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='chapter',
            options={'managed': True, 'ordering': ['book_id', 'order']},
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': True},
        ),
        migrations.CreateModel(
            name='BorrowDetail',
            fields=[
                ('id', models.AutoField(db_column='ma_chi_tiet_muon', primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(db_column='so_luong', default=1)),
                ('status', models.CharField(db_column='trang_thai', default='DangMuon', max_length=50)),
                ('book', models.ForeignKey(db_column='ma_sach', on_delete=django.db.models.deletion.CASCADE, to='api.book')),
                ('borrow', models.ForeignKey(db_column='ma_phieu_muon', on_delete=django.db.models.deletion.CASCADE, related_name='details', to='api.borrow')),
            ],
            options={
                'db_table': 'chi_tiet_muon',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='borrow',
            name='user',
            field=models.ForeignKey(db_column='ma_nguoi_dung', on_delete=django.db.models.deletion.CASCADE, related_name='borrows', to='api.user'),
        ),
    ]
