# Generated by Django 4.2.30 on 2026-05-09 02:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_borrow_alter_book_options_alter_bookreview_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='stock',
            field=models.IntegerField(db_column='so_luong_ton', default=0),
        ),
        migrations.AddField(
            model_name='bookreview',
            name='book',
            field=models.ForeignKey(blank=True, db_column='ma_sach', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.book'),
        ),
        migrations.AddField(
            model_name='bookreview',
            name='user',
            field=models.ForeignKey(blank=True, db_column='ma_nguoi_dung', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_reviews', to='api.user'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='book',
            field=models.ForeignKey(db_column='ma_sach', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='api.book'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.CharField(blank=True, db_column='link_anh_dai_dien', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, db_column='ngay_tao', default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(db_column='email', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(db_column='mat_khau', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(db_column='vai_tro', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.AutoField(db_column='ma_nguoi_dung', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_column='ten_dang_nhap', max_length=255, unique=True),
        ),
    ]
